INSERT INTO USERS values (1, 'admin@admin', '1111', 0, SYSDATE, SYSDATE, 1, 1, 0, 'naver', '관리자', '저는관리자에요', '사진없음', 2021, 01, 29, 0, 0);

INSERT INTO BOARD_KNOWHOW VALUES (1, '안녕' ,'안녕하세요', SYSDATE, 1, 0, 0, 20);
INSERT INTO BOARD_KNOWHOW VALUES (2, '임예원' , '뭐죠' , SYSDATE, 1, 0, 0, 30);
INSERT INTO BOARD_KNOWHOW VALUES (3, '식단','식단나열', SYSDATE, 1, 0, 0, 40);

INSERT INTO BOARD_KNOWHOW_TAG VALUES (1, 1, 1);
INSERT INTO BOARD_KNOWHOW_TAG VALUES (2, 2, 0);
INSERT INTO BOARD_KNOWHOW_TAG VALUES (3, 3, 1);

 
