select * from users;
select * from trainer_info;

-- 관리자 1, 일반유저 35, 트레이너 3
INSERT INTO USERS values (users_seq.nextval, 'ziziza93@naver.com', 1111, 0, SYSDATE, SYSDATE, 100, 0, 0, 'kakao', '본계정', '관리자입니다', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'admin@letsports.com', 1111, 0, SYSDATE, SYSDATE, 100, 0, 0, 'kakao', '관리자', '관리자입니다', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user1@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '메롱', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user2@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'kakao', '글쎄요', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user3@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '접니다', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user4@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'google', '운동마니아', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user5@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'facebook', '농구조아', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user6@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'local', '야구만세', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user7@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '신난당', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user8@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'kakao', '나니고레', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user9@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '무슨서비스지', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user10@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'google', '심심해', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user11@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'facebook', '머슬킹', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user12@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'local', '머슬마니아', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user13@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '술술마니아', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user14@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'kakao', '머술쓰', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user15@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '마님하이', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user16@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'google', '마늘맨', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user17@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'facebook', '당근맨', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user18@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'local', '당근좋아', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user19@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '가지좋아', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user20@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'kakao', '씐난다', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user21@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', 'kinggu', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user22@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'google', '캥거루맨', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user23@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'facebook', '캉캉이', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user24@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'local', '좋아요', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user25@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '그냥좋아', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user26@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'kakao', '울지마', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user27@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '슬퍼하쥐망', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user28@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'google', '운동하자', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user29@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'facebook', '같이할래', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user30@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'local', '같이하자구', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user31@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '같이해용', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user32@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'kakao', '하기시러', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user33@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'kkao', '나는조타', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user34@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'local', '나는실타', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'user35@letsports.com', 1111, 2, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '굿굿맨', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'trainer1@letsports.com', 1111, 1, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '쫑트', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'trainer2@letsports.com', 1111, 1, SYSDATE, SYSDATE, 1, 0, 0, 'kakao', '킹트', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO USERS values (users_seq.nextval, 'trainer3@letsports.com', 1111, 1, SYSDATE, SYSDATE, 1, 0, 0, 'naver', '홍트', '잘부탁드려요', null, null, null, null, 0, 0);
INSERT INTO trainer_info values (trainer_info_seq.nextval, 37, 1, '강철종', '트레이너자격증', '신촌센터', '안녕하세요. 반갑습니다. 잘부탁드립니다.', SYSDATE);
INSERT INTO trainer_info values (trainer_info_seq.nextval, 38, 7, '김갑수', '트레이너자격증', '영등포센터', '안녕하세요. 반갑습니다. 잘부탁드립니다.', SYSDATE);
INSERT INTO trainer_info values (trainer_info_seq.nextval, 39, 10, '홍백현', '트레이너자격증', '강남센터', '안녕하세요. 반갑습니다. 잘부탁드립니다.', SYSDATE);